### ISSUE TITLE
Local config for separate projects

### ISSUE THREAD

**Issue by siiron** [FrancisVega/fractalcomp#2]
Is there a way to use this with a local config in different projects?

Let's say I want one base configuration for project A, and another base configuration for project B. I'm looking for a way to tell the app "If you find a local config within this project, use that, if not use the default".

**Comment by FrancisVega** [comment]
Hi!

I'm sorry, the script just allow *one* cofiguration. All you can do is within from ~/fractalcomp folder.

Anyway, I think is a good idea to have a *local* configuration, for example in the current directory (the project directory ..)

I'll think about it

Thanks!

**Comment by FrancisVega** [comment]
Hi! Now fractalcomp behaviour is root project based :)
